import numpy as np
from scipy.ndimage import gaussian_filter1d
import pandas as pd
import os
import itertools

def create_trial_data(duration, time_step, output_dir, use_normalized_time, temperature_random_layers, convection_parameters, temperature_time_curves):
    """
    Generates trial input data for temperature and convection coefficient time series, with optional randomization.
    Creates a trial for every combination of temperature time curve and convection coefficient parameter set.
    Each trial is saved as a CSV file in the specified output directory.
    """

    ### do not modify below here ###

    #convert curves to numpy arrays and adjust time if needed
    temperature_time_curves = [np.array(curve) for curve in temperature_time_curves]

    if use_normalized_time:
        for temp_curve in temperature_time_curves:
            temp_curve[:,0] = temp_curve[:,0] * duration  # Normalize time in curve definitions to [0, 1]

    def get_convection_coeff(time, temperature, coeffs):
        base_coeff = coeffs[0]
        temp_coeff = coeffs[1]
        return base_coeff + temp_coeff * temperature

    os.makedirs(output_dir, exist_ok=True)

    time = np.arange(0, duration + time_step, time_step)  # Time in seconds

    # Generate and save CSV files
    # this loop goes over all combinations of curves
    for (i, temp_curve), (j, conv_params) in itertools.product(enumerate(temperature_time_curves), enumerate(convection_parameters)):
        temperatures = np.interp(time, temp_curve[:, 0], temp_curve[:, 1])
        
        noise_layers_list = []
        if len(temperature_random_layers) > 0:
            for period, std in temperature_random_layers:
                noise = generate_smooth_noise(times=time, period=period, std=std, seed=None)
                noise_layers_list.append(noise)
                temperatures += noise

        convections = get_convection_coeff(time, temperatures, conv_params)

        total_len = len(time)

        data = {
            "time": time,
            "temp": temperatures,
            "conv": convections,
            "temp_curve_time": temp_curve[:,0],
            "temp_curve_temp": temp_curve[:,1],
            "temp_rand_period": temperature_random_layers[:,0],
            "temp_rand_std": temperature_random_layers[:,1],
        }

        for k, v in enumerate(noise_layers_list):
            data[f'temp_noise{k}'] = v

        for k, v in data.items():
            v = np.asarray(v)
            if len(v) < total_len:
                data[k] = np.concatenate([v, np.full(total_len - len(v), np.nan)])
            else:
                data[k] = v[:total_len]


        name = f'trial_temp_{i}_conv_{j}'
        filename = os.path.join(output_dir, f"{name}.csv")
        pd.DataFrame(data).to_csv(filename, index=False)
        print(f"Created {filename}")

def generate_smooth_noise(
    times,
    period=1.0,
    std=1.0,
    seed=None,
):
    """Generates a smooth noise signal with specified period and standard deviation, sampled at given time points.
    The signal is centered around zero (down to random variations) and has an amplitude defined by the standard deviation. There is no strict limit on maximum value.
The noise is generated by applying a Gaussian filter to white noise, which creates correlations in the signal.
Parameters:
    times (array-like): Time points at which to sample the noise.
    period (float): Approximate period of the noise (same units as input times). Thought of as the feature duration.
    std (float): Standard deviation of the noise. Corresponds to typical feature amplitude.
Returns:
    numpy.ndarray: Smooth noise signal sampled at the specified time points.
"""
    
    rng = np.random.default_rng(seed=seed)

    # smoothing must have fixed time steps
    t = np.linspace(times[0],times[-1], len(times))
    dt = t[1] - t[0]

    sigma = period/(dt*2*np.pi)  # Convert desired period to Gaussian filter sigma

    #needed to adjust std of the smoothed noise to match desired std, since smoothing reduces variance. Derived from properties of Gaussian filter.
    std_noise = std * np.sqrt(2*np.sqrt(np.pi)*sigma)
    
    white_noise = rng.normal(0, std_noise, len(t))
    
    # Apply smoothing (correlation control)
    noise = gaussian_filter1d(white_noise, sigma = sigma)
    
    return np.interp(times, t, noise)

if __name__ == "__main__":
    output_dir = "solver_inputs"
    duration = 14400  # 4 hours in seconds
    time_step = 50  # time step in seconds
    use_normalized_time = True # if True, time is normalized to [0, 1] for each curve. If False, time is in seconds.


    # period (noise feature duration in seconds), standard deviation (amplitude in C)
    temperature_random_layers = np.array([
        (10000, 30),
        (4000, 15),
        (1000, 8),
        (400, 2)
    ])

    # Convection coefficient in W/m²K,
    # terms: [constant, temperature coefficient (per input temperature °C)]
    convection_parameters = [
        [20, 0.05],
        # [30, 0.02]
    ]

    # all temperature time tables to be generated.
    # time (s), temperature (C)
    temperature_time_curves = [
        [
        [0, 100],
        [0.5, 300],
        [1, 300]
        ],
        # [
        # [0, 100],
        # [0.5, 300],
        # [1, 200]
        # ]
    ]
    create_trial_data(duration, time_step, output_dir, use_normalized_time, temperature_random_layers, convection_parameters, temperature_time_curves)